import type { CompactDesign, ProjectState } from '../types'
import { expandRuns } from './runs'

export const SAMPLE_DESIGN: CompactDesign = {
  version: 1,
  name: 'The Brassbound Mountain',
  width: 32,
  height: 32,
  background: 'obsidian',
  runs: [
    { y: 3, x: 8, length: 16, material: 'native-gold' },
    { y: 4, x: 7, length: 18, material: 'native-gold' },
    { y: 5, x: 6, length: 4, material: 'native-gold' },
    { y: 5, x: 22, length: 4, material: 'native-gold' },
    { y: 6, x: 5, length: 3, material: 'native-gold' },
    { y: 6, x: 24, length: 3, material: 'native-gold' },
    { y: 7, x: 4, length: 3, material: 'native-gold' },
    { y: 7, x: 25, length: 3, material: 'native-gold' },
    { y: 8, x: 3, length: 3, material: 'native-gold' },
    { y: 8, x: 26, length: 3, material: 'native-gold' },
    { y: 9, x: 3, length: 2, material: 'native-gold' },
    { y: 9, x: 27, length: 2, material: 'native-gold' },
    { y: 10, x: 2, length: 2, material: 'native-gold' },
    { y: 10, x: 28, length: 2, material: 'native-gold' },
    { y: 11, x: 2, length: 2, material: 'native-gold' },
    { y: 11, x: 28, length: 2, material: 'native-gold' },
    { y: 12, x: 2, length: 2, material: 'native-gold' },
    { y: 12, x: 28, length: 2, material: 'native-gold' },
    { y: 13, x: 11, length: 10, material: 'native-gold' },
    { y: 14, x: 9, length: 14, material: 'native-gold' },
    { y: 15, x: 8, length: 5, material: 'native-gold' },
    { y: 15, x: 19, length: 5, material: 'native-gold' },
    { y: 16, x: 7, length: 4, material: 'native-gold' },
    { y: 16, x: 21, length: 4, material: 'native-gold' },
    { y: 17, x: 6, length: 4, material: 'native-gold' },
    { y: 17, x: 22, length: 4, material: 'native-gold' },
    { y: 18, x: 5, length: 4, material: 'native-gold' },
    { y: 18, x: 23, length: 4, material: 'native-gold' },
    { y: 19, x: 4, length: 4, material: 'native-gold' },
    { y: 19, x: 24, length: 4, material: 'native-gold' },
    { y: 20, x: 4, length: 3, material: 'native-gold' },
    { y: 20, x: 25, length: 3, material: 'native-gold' },
    { y: 21, x: 3, length: 3, material: 'native-gold' },
    { y: 21, x: 26, length: 3, material: 'native-gold' },
    { y: 22, x: 3, length: 2, material: 'native-gold' },
    { y: 22, x: 27, length: 2, material: 'native-gold' },
    { y: 23, x: 2, length: 2, material: 'native-gold' },
    { y: 23, x: 28, length: 2, material: 'native-gold' },
    { y: 24, x: 2, length: 28, material: 'native-gold' },
    { y: 25, x: 3, length: 26, material: 'native-gold' },
    { y: 26, x: 5, length: 22, material: 'native-gold' },
    { y: 27, x: 8, length: 16, material: 'native-gold' },
    { y: 10, x: 14, length: 4, material: 'malachite' },
    { y: 11, x: 13, length: 6, material: 'malachite' },
    { y: 12, x: 14, length: 4, material: 'malachite' },
    { y: 17, x: 14, length: 4, material: 'malachite' },
    { y: 18, x: 13, length: 6, material: 'malachite' },
    { y: 19, x: 14, length: 4, material: 'malachite' },
  ],
}

export const sampleProject = (): ProjectState => ({
  version: 1,
  name: SAMPLE_DESIGN.name,
  width: SAMPLE_DESIGN.width,
  height: SAMPLE_DESIGN.height,
  background: SAMPLE_DESIGN.background,
  cells: expandRuns(SAMPLE_DESIGN),
  renderMode: 'color',
  gridVisible: true,
  zoom: 18,
  selectedMaterial: 'native-gold',
})
