// Canonical Dwarf Fortress material labels and representative planning colors.
// The color palette is retained from the original planning prototype; no third-party image data is stored here.
export const materialPalette = [
  { id: 'andesite', name: 'Andesite', category: 'Stone', colorHex: '#545a5f' },
  { id: 'gneiss', name: 'Gneiss', category: 'Stone', colorHex: '#61594c' },
  { id: 'sandstone', name: 'Sandstone', category: 'Stone', colorHex: '#5f4b46' },
  { id: 'borax', name: 'Borax', category: 'Stone', colorHex: '#545e71' },
  { id: 'garnierite', name: 'Garnierite', category: 'Stone', colorHex: '#51556e' },
  { id: 'lignite', name: 'Lignite', category: 'Stone', colorHex: '#4c5363' },
  { id: 'native-platinum', name: 'Native Platinum', category: 'Stone', colorHex: '#545e71' },
  { id: 'raw-adamantine', name: 'Raw Adamantine', category: 'Stone', colorHex: '#486277' },
  { id: 'sylvite', name: 'Sylvite', category: 'Stone', colorHex: '#614340' },
  { id: 'basalt', name: 'Basalt', category: 'Stone', colorHex: '#3d3e3f' },
  { id: 'granite', name: 'Granite', category: 'Stone', colorHex: '#51505d' },
  { id: 'schist', name: 'Schist', category: 'Stone', colorHex: '#373037' },
  { id: 'brimstone', name: 'Brimstone', category: 'Stone', colorHex: '#6b6842' },
  { id: 'graphite', name: 'Graphite', category: 'Stone', colorHex: '#31363c' },
  { id: 'limonite', name: 'Limonite', category: 'Stone', colorHex: '#5f4b46' },
  { id: 'native-silver', name: 'Native Silver', category: 'Stone', colorHex: '#545e71' },
  { id: 'realgar', name: 'Realgar', category: 'Stone', colorHex: '#543836' },
  { id: 'talc', name: 'Talc', category: 'Stone', colorHex: '#685c53' },
  { id: 'chalk', name: 'Chalk', category: 'Stone', colorHex: '#685c53' },
  { id: 'limestone', name: 'Limestone', category: 'Stone', colorHex: '#545e71' },
  { id: 'shale', name: 'Shale', category: 'Stone', colorHex: '#403e3d' },
  { id: 'calcite', name: 'Calcite', category: 'Stone', colorHex: '#61594c' },
  { id: 'gypsum', name: 'Gypsum', category: 'Stone', colorHex: '#4f4846' },
  { id: 'magnetite', name: 'Magnetite', category: 'Stone', colorHex: '#545a5f' },
  { id: 'olivine', name: 'Olivine', category: 'Stone', colorHex: '#60663e' },
  { id: 'rutile', name: 'Rutile', category: 'Stone', colorHex: '#61594c' },
  { id: 'tetrahedrite', name: 'Tetrahedrite', category: 'Stone', colorHex: '#545e71' },
  { id: 'chert', name: 'Chert', category: 'Stone', colorHex: '#464544' },
  { id: 'marble', name: 'Marble', category: 'Stone', colorHex: '#7a828c' },
  { id: 'siltstone', name: 'Siltstone', category: 'Stone', colorHex: '#685c53' },
  { id: 'cassiterite', name: 'Cassiterite', category: 'Stone', colorHex: '#545a5f' },
  { id: 'hematite', name: 'Hematite', category: 'Stone', colorHex: '#503343' },
  { id: 'malachite', name: 'Malachite', category: 'Stone', colorHex: '#325f52' },
  { id: 'orpiment', name: 'Orpiment', category: 'Stone', colorHex: '#81613b' },
  { id: 'saltpeter', name: 'Saltpeter', category: 'Stone', colorHex: '#6d6b5f' },
  { id: 'claystone', name: 'Claystone', category: 'Stone', colorHex: '#3e363b' },
  { id: 'mudstone', name: 'Mudstone', category: 'Stone', colorHex: '#545a5f' },
  { id: 'slate', name: 'Slate', category: 'Stone', colorHex: '#4a4041' },
  { id: 'chromite', name: 'Chromite', category: 'Stone', colorHex: '#292d43' },
  { id: 'hornblende', name: 'Hornblende', category: 'Stone', colorHex: '#545a5f' },
  { id: 'marcasite', name: 'Marcasite', category: 'Stone', colorHex: '#4c4932' },
  { id: 'orthoclase', name: 'Orthoclase', category: 'Stone', colorHex: '#493a41' },
  { id: 'selenite', name: 'Selenite', category: 'Stone', colorHex: '#6d6b5f' },
  { id: 'conglomerate', name: 'Conglomerate', category: 'Stone', colorHex: '#443f3f' },
  { id: 'obsidian', name: 'Obsidian', category: 'Stone', colorHex: '#2a2e36' },
  { id: 'alabaster', name: 'Alabaster', category: 'Stone', colorHex: '#6d6b5f' },
  { id: 'cinnabar', name: 'Cinnabar', category: 'Stone', colorHex: '#543836' },
  { id: 'horn-silver', name: 'Horn Silver', category: 'Stone', colorHex: '#524843' },
  { id: 'mica', name: 'Mica', category: 'Stone', colorHex: '#5f4b46' },
  { id: 'periclase', name: 'Periclase', category: 'Stone', colorHex: '#465035' },
  { id: 'serpentine', name: 'Serpentine', category: 'Stone', colorHex: '#465035' },
  { id: 'dacite', name: 'Dacite', category: 'Stone', colorHex: '#545e71' },
  { id: 'phyllite', name: 'Phyllite', category: 'Stone', colorHex: '#545a5f' },
  { id: 'alunite', name: 'Alunite', category: 'Stone', colorHex: '#5f4a62' },
  { id: 'bituminous-coal', name: 'Bituminous Coal', category: 'Stone', colorHex: '#2a3037' },
  { id: 'ilmenite', name: 'Ilmenite', category: 'Stone', colorHex: '#474243' },
  { id: 'microcline', name: 'Microcline', category: 'Stone', colorHex: '#486277' },
  { id: 'petrified-wood', name: 'Petrified Wood', category: 'Stone', colorHex: '#5d463f' },
  { id: 'slade', name: 'Slade', category: 'Stone', colorHex: '#2a2e36' },
  { id: 'diorite', name: 'Diorite', category: 'Stone', colorHex: '#545e71' },
  { id: 'quartzite', name: 'Quartzite', category: 'Stone', colorHex: '#6d5e76' },
  { id: 'anhydrite', name: 'Anhydrite', category: 'Stone', colorHex: '#51556e' },
  { id: 'cobaltite', name: 'Cobaltite', category: 'Stone', colorHex: '#31363c' },
  { id: 'jet', name: 'Jet', category: 'Stone', colorHex: '#30364d' },
  { id: 'native-aluminum', name: 'Native Aluminum', category: 'Stone', colorHex: '#6d6b5f' },
  { id: 'pitchblende', name: 'Pitchblende', category: 'Stone', colorHex: '#464d44' },
  { id: 'sphalerite', name: 'Sphalerite', category: 'Stone', colorHex: '#564456' },
  { id: 'dolomite', name: 'Dolomite', category: 'Stone', colorHex: '#5d5159' },
  { id: 'rhyolite', name: 'Rhyolite', category: 'Stone', colorHex: '#4f4846' },
  { id: 'bauxite', name: 'Bauxite', category: 'Stone', colorHex: '#614340' },
  { id: 'cryolite', name: 'Cryolite', category: 'Stone', colorHex: '#4f4846' },
  { id: 'kaolinite', name: 'Kaolinite', category: 'Stone', colorHex: '#61545d' },
  { id: 'native-copper', name: 'Native Copper', category: 'Stone', colorHex: '#554043' },
  { id: 'puddingstone', name: 'Puddingstone', category: 'Stone', colorHex: '#5f4b46' },
  { id: 'satin-spar', name: 'Satin Spar', category: 'Stone', colorHex: '#6d6b5f' },
  { id: 'gabbro', name: 'Gabbro', category: 'Stone', colorHex: '#545a5f' },
  { id: 'rock-salt', name: 'Rock Salt', category: 'Stone', colorHex: '#674e5a' },
  { id: 'bismuthinite', name: 'Bismuthinite', category: 'Stone', colorHex: '#352f3a' },
  { id: 'galena', name: 'Galena', category: 'Stone', colorHex: '#545e71' },
  { id: 'kimberlite', name: 'Kimberlite', category: 'Stone', colorHex: '#415670' },
  { id: 'native-gold', name: 'Native Gold', category: 'Stone', colorHex: '#594944' },
  { id: 'pyrolusite', name: 'Pyrolusite', category: 'Stone', colorHex: '#31363c' },
  { id: 'stibnite', name: 'Stibnite', category: 'Stone', colorHex: '#415670' },
  { id: 'green-glass', name: 'Green Glass', category: 'Glass', colorHex: '#61816d' },
  { id: 'clear-glass', name: 'Clear Glass', category: 'Glass', colorHex: '#737a7e' },
  { id: 'crystal-glass', name: 'Crystal Glass', category: 'Glass', colorHex: '#717985' },
  { id: 'earthenware', name: 'Earthenware', category: 'Ceramic', colorHex: '#5b514e' },
  { id: 'stoneware', name: 'Stoneware', category: 'Ceramic', colorHex: '#3c423c' },
  { id: 'porcelain', name: 'Porcelain', category: 'Ceramic', colorHex: '#6c5c64' },
  { id: 'iron', name: 'Iron', category: 'Metal', colorHex: '#7f7f81' },
  { id: 'lay-pewter', name: 'Lay Pewter', category: 'Metal', colorHex: '#9c9fa7' },
  { id: 'gold', name: 'Gold', category: 'Metal', colorHex: '#897152' },
  { id: 'lead', name: 'Lead', category: 'Metal', colorHex: '#5f5a59' },
  { id: 'silver', name: 'Silver', category: 'Metal', colorHex: '#8d9096' },
  { id: 'aluminum', name: 'Aluminum', category: 'Metal', colorHex: '#9c9fa7' },
  { id: 'copper', name: 'Copper', category: 'Metal', colorHex: '#835849' },
  { id: 'nickel-silver', name: 'Nickel Silver', category: 'Metal', colorHex: '#8d9096' },
  { id: 'nickel', name: 'Nickel', category: 'Metal', colorHex: '#8d9096' },
  { id: 'billon', name: 'Billon', category: 'Metal', colorHex: '#776c68' },
  { id: 'zinc', name: 'Zinc', category: 'Metal', colorHex: '#8d9096' },
  { id: 'sterling-silver', name: 'Sterling Silver', category: 'Metal', colorHex: '#9c9fa7' },
  { id: 'bronze', name: 'Bronze', category: 'Metal', colorHex: '#70574c' },
  { id: 'black-bronze', name: 'Black Bronze', category: 'Metal', colorHex: '#4b4c4e' },
  { id: 'brass', name: 'Brass', category: 'Metal', colorHex: '#807351' },
  { id: 'rose-gold', name: 'Rose Gold', category: 'Metal', colorHex: '#946971' },
  { id: 'steel', name: 'Steel', category: 'Metal', colorHex: '#888c98' },
  { id: 'bismuth', name: 'Bismuth', category: 'Metal', colorHex: '#826682' },
  { id: 'pig-iron', name: 'Pig Iron', category: 'Metal', colorHex: '#5f5a59' },
  { id: 'bismuth-bronze', name: 'Bismuth Bronze', category: 'Metal', colorHex: '#83796e' },
  { id: 'platinum', name: 'Platinum', category: 'Metal', colorHex: '#9c9fa7' },
  { id: 'adamantine', name: 'Adamantine', category: 'Metal', colorHex: '#6f8997' },
  { id: 'electrum', name: 'Electrum', category: 'Metal', colorHex: '#6e5948' },
  { id: 'tin', name: 'Tin', category: 'Metal', colorHex: '#8d9096' },
  { id: 'fine-pewter', name: 'Fine Pewter', category: 'Metal', colorHex: '#8d9096' },
  { id: 'trifle-pewter', name: 'Trifle Pewter', category: 'Metal', colorHex: '#5f5a59' },
]
