// Generated by scripts/generate-materials.mjs from the original procedural texture generator. Do not edit by hand.
export type MaterialCategory = 'Stone' | 'Glass' | 'Ceramic' | 'Metal'

export interface Material {
  id: string
  name: string
  category: MaterialCategory
  colorHex: string
  swatchUrl: string
  width: 48
  height: 48
  textureSha256: string
}

export const TEXTURE_GENERATOR = {
  "kind": "original-procedural",
  "version": 1,
  "tileSize": 48
} as const

export const MATERIALS: Material[] = [
  {
    "id": "andesite",
    "name": "Andesite",
    "category": "Stone",
    "colorHex": "#545a5f",
    "swatchUrl": "/materials/andesite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "b4b05ee2a8277ce103a7e91b1cd31fd9643530b7957238863b4c728948149509"
  },
  {
    "id": "gneiss",
    "name": "Gneiss",
    "category": "Stone",
    "colorHex": "#61594c",
    "swatchUrl": "/materials/gneiss.png",
    "width": 48,
    "height": 48,
    "textureSha256": "a30dd0b6262731394528f2d148f55e46b45a8f7ce3dc70a117248874a3f6e040"
  },
  {
    "id": "sandstone",
    "name": "Sandstone",
    "category": "Stone",
    "colorHex": "#5f4b46",
    "swatchUrl": "/materials/sandstone.png",
    "width": 48,
    "height": 48,
    "textureSha256": "aa35ca81961f11a3d0a319889cf104d2326b79cfaa014023745939842e23c0d5"
  },
  {
    "id": "borax",
    "name": "Borax",
    "category": "Stone",
    "colorHex": "#545e71",
    "swatchUrl": "/materials/borax.png",
    "width": 48,
    "height": 48,
    "textureSha256": "773901a74b5f5bc2c19578fdddfec807eee8f88f22d088c7b83e91b3d424de9e"
  },
  {
    "id": "garnierite",
    "name": "Garnierite",
    "category": "Stone",
    "colorHex": "#51556e",
    "swatchUrl": "/materials/garnierite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "8d16854211e4ee54f442c0b09f67a84078d6c9787889160c051e6b1a91fc04a4"
  },
  {
    "id": "lignite",
    "name": "Lignite",
    "category": "Stone",
    "colorHex": "#4c5363",
    "swatchUrl": "/materials/lignite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "52481e030c02c187cd69f4a0d712e10470f3706060ac6c8ea02916ac08415a77"
  },
  {
    "id": "native-platinum",
    "name": "Native Platinum",
    "category": "Stone",
    "colorHex": "#545e71",
    "swatchUrl": "/materials/native-platinum.png",
    "width": 48,
    "height": 48,
    "textureSha256": "c887b78db5de72f3346924383f525abc74702d77bd56a30b9fc0dddf5b158b17"
  },
  {
    "id": "raw-adamantine",
    "name": "Raw Adamantine",
    "category": "Stone",
    "colorHex": "#486277",
    "swatchUrl": "/materials/raw-adamantine.png",
    "width": 48,
    "height": 48,
    "textureSha256": "9a737223895b8f23d2b937c592d3b7311e910e80f5d64d1cae2b96a64e6cdcd3"
  },
  {
    "id": "sylvite",
    "name": "Sylvite",
    "category": "Stone",
    "colorHex": "#614340",
    "swatchUrl": "/materials/sylvite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "982c3343208ed5e6f331b6120df19a9368267b23c716eb996ebb0cd28e27b840"
  },
  {
    "id": "basalt",
    "name": "Basalt",
    "category": "Stone",
    "colorHex": "#3d3e3f",
    "swatchUrl": "/materials/basalt.png",
    "width": 48,
    "height": 48,
    "textureSha256": "0b255c96b53af2e8248478673196266a763e219b03fa21b8a5b59d56578294dd"
  },
  {
    "id": "granite",
    "name": "Granite",
    "category": "Stone",
    "colorHex": "#51505d",
    "swatchUrl": "/materials/granite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f79e80e223d864cbbd0fcdf6f5016ad02102c70314d5943e26708abe046b4d25"
  },
  {
    "id": "schist",
    "name": "Schist",
    "category": "Stone",
    "colorHex": "#373037",
    "swatchUrl": "/materials/schist.png",
    "width": 48,
    "height": 48,
    "textureSha256": "00ef9a4414f5f2f1d5e192bc403f12645704fbf61a29510f740561de587d5bc9"
  },
  {
    "id": "brimstone",
    "name": "Brimstone",
    "category": "Stone",
    "colorHex": "#6b6842",
    "swatchUrl": "/materials/brimstone.png",
    "width": 48,
    "height": 48,
    "textureSha256": "6dce6c4f4fb223a07bc915a3edb4c16c0b004df3974b0dcb6b81e0fe48d907fa"
  },
  {
    "id": "graphite",
    "name": "Graphite",
    "category": "Stone",
    "colorHex": "#31363c",
    "swatchUrl": "/materials/graphite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f9a074a25e848f102920301964775a83d57001a2b0f720bc2f31dabc3504e407"
  },
  {
    "id": "limonite",
    "name": "Limonite",
    "category": "Stone",
    "colorHex": "#5f4b46",
    "swatchUrl": "/materials/limonite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "b43cdfcea8648eb568a75fdc872b2d8d793baea3095af4c911fa523ed3a39b80"
  },
  {
    "id": "native-silver",
    "name": "Native Silver",
    "category": "Stone",
    "colorHex": "#545e71",
    "swatchUrl": "/materials/native-silver.png",
    "width": 48,
    "height": 48,
    "textureSha256": "c68977d15e09974f3941ed969fa524faa190e75c70f085202e7c727bc20bf74f"
  },
  {
    "id": "realgar",
    "name": "Realgar",
    "category": "Stone",
    "colorHex": "#543836",
    "swatchUrl": "/materials/realgar.png",
    "width": 48,
    "height": 48,
    "textureSha256": "71703926491699afc73d27f24f6d5cc67dcbf18e91c53646e8aab63c6e027a9c"
  },
  {
    "id": "talc",
    "name": "Talc",
    "category": "Stone",
    "colorHex": "#685c53",
    "swatchUrl": "/materials/talc.png",
    "width": 48,
    "height": 48,
    "textureSha256": "c4232366d14805ce5a74784e64ac4e085386a98692fddba6306e473c2b18f328"
  },
  {
    "id": "chalk",
    "name": "Chalk",
    "category": "Stone",
    "colorHex": "#685c53",
    "swatchUrl": "/materials/chalk.png",
    "width": 48,
    "height": 48,
    "textureSha256": "dcfb261b1706e8a49ee91d4ae5e719c500ca344f4b4629208c300ec71fa587ff"
  },
  {
    "id": "limestone",
    "name": "Limestone",
    "category": "Stone",
    "colorHex": "#545e71",
    "swatchUrl": "/materials/limestone.png",
    "width": 48,
    "height": 48,
    "textureSha256": "fd5af7b1e33fad4320064260dd47a50f091c6d71d2b37c9aa7fae3e1dcabe384"
  },
  {
    "id": "shale",
    "name": "Shale",
    "category": "Stone",
    "colorHex": "#403e3d",
    "swatchUrl": "/materials/shale.png",
    "width": 48,
    "height": 48,
    "textureSha256": "ae7a73a8ad05ed962d85b865330a8100cb3494c78e31bba6fd7d8309a19e60e9"
  },
  {
    "id": "calcite",
    "name": "Calcite",
    "category": "Stone",
    "colorHex": "#61594c",
    "swatchUrl": "/materials/calcite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "c4fc16bc26efeac358db1eafff247fe37e48fa2544371953b72d819055423ef4"
  },
  {
    "id": "gypsum",
    "name": "Gypsum",
    "category": "Stone",
    "colorHex": "#4f4846",
    "swatchUrl": "/materials/gypsum.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f76c4386542227f59fef94c0b9b1bb0810097839b0596cd2c0540adfcddef924"
  },
  {
    "id": "magnetite",
    "name": "Magnetite",
    "category": "Stone",
    "colorHex": "#545a5f",
    "swatchUrl": "/materials/magnetite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "b223bc972bc4017f90fd0f48ed057ae3ca215d9cfa49469d2c4f4b63d48303b3"
  },
  {
    "id": "olivine",
    "name": "Olivine",
    "category": "Stone",
    "colorHex": "#60663e",
    "swatchUrl": "/materials/olivine.png",
    "width": 48,
    "height": 48,
    "textureSha256": "c19fe9d4aedec82071be17ba8ea6dcf6d1823db340864c5e155cb0d472ec92e2"
  },
  {
    "id": "rutile",
    "name": "Rutile",
    "category": "Stone",
    "colorHex": "#61594c",
    "swatchUrl": "/materials/rutile.png",
    "width": 48,
    "height": 48,
    "textureSha256": "865875f496a85f60634d95726dbdcdadd8e42d5a716b8161003750391fe04d0c"
  },
  {
    "id": "tetrahedrite",
    "name": "Tetrahedrite",
    "category": "Stone",
    "colorHex": "#545e71",
    "swatchUrl": "/materials/tetrahedrite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "e7ebbdd53c977f67a5c163c0d3dfa772c41491388218aef0d4c54bda3d1498ea"
  },
  {
    "id": "chert",
    "name": "Chert",
    "category": "Stone",
    "colorHex": "#464544",
    "swatchUrl": "/materials/chert.png",
    "width": 48,
    "height": 48,
    "textureSha256": "1b2b203cc479082b2317b2e1dc8af74ee57ffde722409985ad2d7e1720879a80"
  },
  {
    "id": "marble",
    "name": "Marble",
    "category": "Stone",
    "colorHex": "#7a828c",
    "swatchUrl": "/materials/marble.png",
    "width": 48,
    "height": 48,
    "textureSha256": "4a4d2c874b31782f07c234229649cd78ff111a420d01282fd1a971ba98474cf9"
  },
  {
    "id": "siltstone",
    "name": "Siltstone",
    "category": "Stone",
    "colorHex": "#685c53",
    "swatchUrl": "/materials/siltstone.png",
    "width": 48,
    "height": 48,
    "textureSha256": "a7e7d952d741c1d0d3e404e0602d31686eb7deddf490dd1d580dca5630e271b2"
  },
  {
    "id": "cassiterite",
    "name": "Cassiterite",
    "category": "Stone",
    "colorHex": "#545a5f",
    "swatchUrl": "/materials/cassiterite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "b160f1966bb39650266b5d450bf56b3f609ecd5f96b18974a5e759d0aea20128"
  },
  {
    "id": "hematite",
    "name": "Hematite",
    "category": "Stone",
    "colorHex": "#503343",
    "swatchUrl": "/materials/hematite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "8ae9b598383d6b442709c97ff59d828a1e4643de77d2327c4845e729759b93d9"
  },
  {
    "id": "malachite",
    "name": "Malachite",
    "category": "Stone",
    "colorHex": "#325f52",
    "swatchUrl": "/materials/malachite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "d05e5d6299a8b387d81f10d73936bd564457132b43bc561025bc5bb2136e25c6"
  },
  {
    "id": "orpiment",
    "name": "Orpiment",
    "category": "Stone",
    "colorHex": "#81613b",
    "swatchUrl": "/materials/orpiment.png",
    "width": 48,
    "height": 48,
    "textureSha256": "6236b64fb00eb4dcd8d413f60a75f5b714a1e871a7ca92b30bcc5475661480a8"
  },
  {
    "id": "saltpeter",
    "name": "Saltpeter",
    "category": "Stone",
    "colorHex": "#6d6b5f",
    "swatchUrl": "/materials/saltpeter.png",
    "width": 48,
    "height": 48,
    "textureSha256": "bb39fc2c2c6da2410f34c7b1c0da34bd63c423212069c9ac7813d9beaf6d000a"
  },
  {
    "id": "claystone",
    "name": "Claystone",
    "category": "Stone",
    "colorHex": "#3e363b",
    "swatchUrl": "/materials/claystone.png",
    "width": 48,
    "height": 48,
    "textureSha256": "04a01179b850c85cec3f853a6ee0c8ebc8b02e120a1c6a3841f2ba3a23aa7e47"
  },
  {
    "id": "mudstone",
    "name": "Mudstone",
    "category": "Stone",
    "colorHex": "#545a5f",
    "swatchUrl": "/materials/mudstone.png",
    "width": 48,
    "height": 48,
    "textureSha256": "93f57b9f99f7b6b29abed9d8fd4d2a4cf6171193e3a7162676bf50afb0303a41"
  },
  {
    "id": "slate",
    "name": "Slate",
    "category": "Stone",
    "colorHex": "#4a4041",
    "swatchUrl": "/materials/slate.png",
    "width": 48,
    "height": 48,
    "textureSha256": "93180b2f4a64d0544edc89d8858360d8933201170c9c97cef41cdf859241dd1e"
  },
  {
    "id": "chromite",
    "name": "Chromite",
    "category": "Stone",
    "colorHex": "#292d43",
    "swatchUrl": "/materials/chromite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "1e7186561e8108224eb3cfdcd106370e18c72a0c9b4b74f383ba22b7f91105b1"
  },
  {
    "id": "hornblende",
    "name": "Hornblende",
    "category": "Stone",
    "colorHex": "#545a5f",
    "swatchUrl": "/materials/hornblende.png",
    "width": 48,
    "height": 48,
    "textureSha256": "1bf9bbc466ee21b7222a07f7e3a0342839f0a9af464d382838d20e5fc9a2b3e8"
  },
  {
    "id": "marcasite",
    "name": "Marcasite",
    "category": "Stone",
    "colorHex": "#4c4932",
    "swatchUrl": "/materials/marcasite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "91f69d37750e227d07f1c8822df98789f6f1b9639dde4eb3d538fe50a71084a7"
  },
  {
    "id": "orthoclase",
    "name": "Orthoclase",
    "category": "Stone",
    "colorHex": "#493a41",
    "swatchUrl": "/materials/orthoclase.png",
    "width": 48,
    "height": 48,
    "textureSha256": "a93998e7bc4d0be290640e61bc1ed811de1009b6c9423180e0ab07807874b4c4"
  },
  {
    "id": "selenite",
    "name": "Selenite",
    "category": "Stone",
    "colorHex": "#6d6b5f",
    "swatchUrl": "/materials/selenite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "58f32a8890c78584a8de20f3980105b64f2fffd1c81adff4237dbef7adbdf017"
  },
  {
    "id": "conglomerate",
    "name": "Conglomerate",
    "category": "Stone",
    "colorHex": "#443f3f",
    "swatchUrl": "/materials/conglomerate.png",
    "width": 48,
    "height": 48,
    "textureSha256": "48f1aeebb7d298029317efc0a42208657d3ee49c9c889cef6a325147b8e30d9a"
  },
  {
    "id": "obsidian",
    "name": "Obsidian",
    "category": "Stone",
    "colorHex": "#2a2e36",
    "swatchUrl": "/materials/obsidian.png",
    "width": 48,
    "height": 48,
    "textureSha256": "7ed56c88a9b1840ff1a6750608a47aff863003af3329923f6aa516f77614b113"
  },
  {
    "id": "alabaster",
    "name": "Alabaster",
    "category": "Stone",
    "colorHex": "#6d6b5f",
    "swatchUrl": "/materials/alabaster.png",
    "width": 48,
    "height": 48,
    "textureSha256": "9a63f6287bd78c49925ff1336750528600b0cd42711c147d81f4374775115e81"
  },
  {
    "id": "cinnabar",
    "name": "Cinnabar",
    "category": "Stone",
    "colorHex": "#543836",
    "swatchUrl": "/materials/cinnabar.png",
    "width": 48,
    "height": 48,
    "textureSha256": "de2b53718718d4da2685f02e589c5d340b3d255640e9efcd85300836c2180650"
  },
  {
    "id": "horn-silver",
    "name": "Horn Silver",
    "category": "Stone",
    "colorHex": "#524843",
    "swatchUrl": "/materials/horn-silver.png",
    "width": 48,
    "height": 48,
    "textureSha256": "841067d0e430e05a1bd231b70048d1ae1b6ea32404924012ab805e43914ae579"
  },
  {
    "id": "mica",
    "name": "Mica",
    "category": "Stone",
    "colorHex": "#5f4b46",
    "swatchUrl": "/materials/mica.png",
    "width": 48,
    "height": 48,
    "textureSha256": "c277e5c101c0b8e43f9de5621834eb95277ef052c755b51b319cf8290a185e47"
  },
  {
    "id": "periclase",
    "name": "Periclase",
    "category": "Stone",
    "colorHex": "#465035",
    "swatchUrl": "/materials/periclase.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f999186fc25a8321fa01610888134b0faeb3fabca37a944fff9743693af0f207"
  },
  {
    "id": "serpentine",
    "name": "Serpentine",
    "category": "Stone",
    "colorHex": "#465035",
    "swatchUrl": "/materials/serpentine.png",
    "width": 48,
    "height": 48,
    "textureSha256": "5febc36e95334b785f677fc29f58e8060215dff8df4037811b3753067431e7c7"
  },
  {
    "id": "dacite",
    "name": "Dacite",
    "category": "Stone",
    "colorHex": "#545e71",
    "swatchUrl": "/materials/dacite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "4968cedecde2c91b533e1dac2e518289ab2aa342105aab348649b6bf1e3d0d81"
  },
  {
    "id": "phyllite",
    "name": "Phyllite",
    "category": "Stone",
    "colorHex": "#545a5f",
    "swatchUrl": "/materials/phyllite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "cac11fe34ca383b760b57329a926202feaef99f9a63eebc67d5c4c5d169c9ab1"
  },
  {
    "id": "alunite",
    "name": "Alunite",
    "category": "Stone",
    "colorHex": "#5f4a62",
    "swatchUrl": "/materials/alunite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "39bbab781ce19640d2859a1bb386eb8e86f5f76db91e5258c2113861e62ab21a"
  },
  {
    "id": "bituminous-coal",
    "name": "Bituminous Coal",
    "category": "Stone",
    "colorHex": "#2a3037",
    "swatchUrl": "/materials/bituminous-coal.png",
    "width": 48,
    "height": 48,
    "textureSha256": "0a129896ca628f070a9fb0b6acf0fdb4b74470303276194f6e10164373f3a68a"
  },
  {
    "id": "ilmenite",
    "name": "Ilmenite",
    "category": "Stone",
    "colorHex": "#474243",
    "swatchUrl": "/materials/ilmenite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f6db6407d92f399a2e948511c1bf93ce2f088e523b2a0b8c949fcb0c87b2a28c"
  },
  {
    "id": "microcline",
    "name": "Microcline",
    "category": "Stone",
    "colorHex": "#486277",
    "swatchUrl": "/materials/microcline.png",
    "width": 48,
    "height": 48,
    "textureSha256": "54b058e9d666167ee225b6bf8583539ceadaa78b7abbabac63b0d9cd275ae09c"
  },
  {
    "id": "petrified-wood",
    "name": "Petrified Wood",
    "category": "Stone",
    "colorHex": "#5d463f",
    "swatchUrl": "/materials/petrified-wood.png",
    "width": 48,
    "height": 48,
    "textureSha256": "caea1aff259dc00b6af3cb6a3d3bdf476f655c7d24929760d6821a950a082fd7"
  },
  {
    "id": "slade",
    "name": "Slade",
    "category": "Stone",
    "colorHex": "#2a2e36",
    "swatchUrl": "/materials/slade.png",
    "width": 48,
    "height": 48,
    "textureSha256": "035eb9de5034ba2db1e47ab537a8a4c490fd93eff68bd1206b9f9cbf3d8961a7"
  },
  {
    "id": "diorite",
    "name": "Diorite",
    "category": "Stone",
    "colorHex": "#545e71",
    "swatchUrl": "/materials/diorite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "acb6f3caedb57268cb9573fd53d6e014f4f31ba173b69e4d0711ecdc101b52a5"
  },
  {
    "id": "quartzite",
    "name": "Quartzite",
    "category": "Stone",
    "colorHex": "#6d5e76",
    "swatchUrl": "/materials/quartzite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "00cc27b619b2662d7b67a420652c3f8ab72de8e7c6c7b5a1983cee305fb5ab15"
  },
  {
    "id": "anhydrite",
    "name": "Anhydrite",
    "category": "Stone",
    "colorHex": "#51556e",
    "swatchUrl": "/materials/anhydrite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "356f03bfb651613b9bb726a57be2102f8c71b72d24bc7d362c6389f6ea4de81d"
  },
  {
    "id": "cobaltite",
    "name": "Cobaltite",
    "category": "Stone",
    "colorHex": "#31363c",
    "swatchUrl": "/materials/cobaltite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "8c81112f5bf1100bcb2e9e2646b6865d32444e815313588ac77b0dc1695e81ae"
  },
  {
    "id": "jet",
    "name": "Jet",
    "category": "Stone",
    "colorHex": "#30364d",
    "swatchUrl": "/materials/jet.png",
    "width": 48,
    "height": 48,
    "textureSha256": "c1b7104ebee7ccb8c28fe4b8475635362633e9408b19cc7843c65e40be490476"
  },
  {
    "id": "native-aluminum",
    "name": "Native Aluminum",
    "category": "Stone",
    "colorHex": "#6d6b5f",
    "swatchUrl": "/materials/native-aluminum.png",
    "width": 48,
    "height": 48,
    "textureSha256": "8d6d6f845e246567fb20094bff9d3411576075d850e7697a0e47603db838faa1"
  },
  {
    "id": "pitchblende",
    "name": "Pitchblende",
    "category": "Stone",
    "colorHex": "#464d44",
    "swatchUrl": "/materials/pitchblende.png",
    "width": 48,
    "height": 48,
    "textureSha256": "92949a09291ea55e6c1702e006abaecaeaa08b2a69b65501c746088e8f892d9e"
  },
  {
    "id": "sphalerite",
    "name": "Sphalerite",
    "category": "Stone",
    "colorHex": "#564456",
    "swatchUrl": "/materials/sphalerite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "1c3ca5e492e6a60f5a74f7f87a0ae3f9751a320a600b950698123a44cba653d0"
  },
  {
    "id": "dolomite",
    "name": "Dolomite",
    "category": "Stone",
    "colorHex": "#5d5159",
    "swatchUrl": "/materials/dolomite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "0f7a9648533d0b7fec2092e6504fd213e1c4dc9f288d429a771469ce1e37a526"
  },
  {
    "id": "rhyolite",
    "name": "Rhyolite",
    "category": "Stone",
    "colorHex": "#4f4846",
    "swatchUrl": "/materials/rhyolite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "41974389b5f21f356ecce326a95417ff5ba8c27de0e5b5d14e411c5a0597cc4e"
  },
  {
    "id": "bauxite",
    "name": "Bauxite",
    "category": "Stone",
    "colorHex": "#614340",
    "swatchUrl": "/materials/bauxite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "027a0655b14ec43e0f126490de7d49814506e3dabe73a5d9aa0d66f1bc57153f"
  },
  {
    "id": "cryolite",
    "name": "Cryolite",
    "category": "Stone",
    "colorHex": "#4f4846",
    "swatchUrl": "/materials/cryolite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "0265056d9029fd522daa21ef01433c7f4fcf0aef08f807c63cac2d1d506cac27"
  },
  {
    "id": "kaolinite",
    "name": "Kaolinite",
    "category": "Stone",
    "colorHex": "#61545d",
    "swatchUrl": "/materials/kaolinite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "521cbf3e5fad23158d5c67ddc63cae732d6961c4bb8455916371c0c5f57ef98f"
  },
  {
    "id": "native-copper",
    "name": "Native Copper",
    "category": "Stone",
    "colorHex": "#554043",
    "swatchUrl": "/materials/native-copper.png",
    "width": 48,
    "height": 48,
    "textureSha256": "de0bb3293de74a6e81006b723e96a6fcfffe2857054ea9e77405221cc56b3df0"
  },
  {
    "id": "puddingstone",
    "name": "Puddingstone",
    "category": "Stone",
    "colorHex": "#5f4b46",
    "swatchUrl": "/materials/puddingstone.png",
    "width": 48,
    "height": 48,
    "textureSha256": "9f7373ece80dfeddd3f6b9e4c7848a1b76c4353d8065597a8df0c753a5a32cd3"
  },
  {
    "id": "satin-spar",
    "name": "Satin Spar",
    "category": "Stone",
    "colorHex": "#6d6b5f",
    "swatchUrl": "/materials/satin-spar.png",
    "width": 48,
    "height": 48,
    "textureSha256": "ea2976cccaed195bdae19cb3fa586797e944448d5b47acf04c955518a9719724"
  },
  {
    "id": "gabbro",
    "name": "Gabbro",
    "category": "Stone",
    "colorHex": "#545a5f",
    "swatchUrl": "/materials/gabbro.png",
    "width": 48,
    "height": 48,
    "textureSha256": "bde6deb76bb962a078f4c54028311bcb8f5879101f818df9a1285cf7a0f07617"
  },
  {
    "id": "rock-salt",
    "name": "Rock Salt",
    "category": "Stone",
    "colorHex": "#674e5a",
    "swatchUrl": "/materials/rock-salt.png",
    "width": 48,
    "height": 48,
    "textureSha256": "30b63fbfc7d3072c12ac46692dcc537e1860b55d9638da1af28f3dcd0ad3cfe8"
  },
  {
    "id": "bismuthinite",
    "name": "Bismuthinite",
    "category": "Stone",
    "colorHex": "#352f3a",
    "swatchUrl": "/materials/bismuthinite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "4c7cb987cb433ed9fafe2e405bde6f29d98fb57f4870e46cfaf958c0dc704345"
  },
  {
    "id": "galena",
    "name": "Galena",
    "category": "Stone",
    "colorHex": "#545e71",
    "swatchUrl": "/materials/galena.png",
    "width": 48,
    "height": 48,
    "textureSha256": "c3bbf8dfe9c345e4c2f7f16c6599aad28c3785c696fd667ee632a353fea56ad3"
  },
  {
    "id": "kimberlite",
    "name": "Kimberlite",
    "category": "Stone",
    "colorHex": "#415670",
    "swatchUrl": "/materials/kimberlite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "91cab06b6a21772c401a1fdd7c95a0008377ed0636733943719f2c921fbac701"
  },
  {
    "id": "native-gold",
    "name": "Native Gold",
    "category": "Stone",
    "colorHex": "#594944",
    "swatchUrl": "/materials/native-gold.png",
    "width": 48,
    "height": 48,
    "textureSha256": "adeb5414b1ea4ccc7bd2479a779fa4cf6a0787ec0974ac1402f770959c66e175"
  },
  {
    "id": "pyrolusite",
    "name": "Pyrolusite",
    "category": "Stone",
    "colorHex": "#31363c",
    "swatchUrl": "/materials/pyrolusite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "229f8f6000198b3d47f9ec52a2f7da0f2f5dacef333434bcf92a58dfe72758e1"
  },
  {
    "id": "stibnite",
    "name": "Stibnite",
    "category": "Stone",
    "colorHex": "#415670",
    "swatchUrl": "/materials/stibnite.png",
    "width": 48,
    "height": 48,
    "textureSha256": "82d832d5c7f9feb9ef8d7cd391ad630d7def77cad3cb8434867ff7ebd841f1dd"
  },
  {
    "id": "green-glass",
    "name": "Green Glass",
    "category": "Glass",
    "colorHex": "#61816d",
    "swatchUrl": "/materials/green-glass.png",
    "width": 48,
    "height": 48,
    "textureSha256": "03d8a950a7bd7064fe8d1490b0337b754ba842271ca03dc4c0ad9fd3768e77cf"
  },
  {
    "id": "clear-glass",
    "name": "Clear Glass",
    "category": "Glass",
    "colorHex": "#737a7e",
    "swatchUrl": "/materials/clear-glass.png",
    "width": 48,
    "height": 48,
    "textureSha256": "6899e05e8be6098bfc30b32c0227496a5df7ff3191c4f821328efdcc2f087a87"
  },
  {
    "id": "crystal-glass",
    "name": "Crystal Glass",
    "category": "Glass",
    "colorHex": "#717985",
    "swatchUrl": "/materials/crystal-glass.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f2f9489905c6ef24d2ed964ebd11ab00a7d6af30d94eadd080cb8ef5433ecc8a"
  },
  {
    "id": "earthenware",
    "name": "Earthenware",
    "category": "Ceramic",
    "colorHex": "#5b514e",
    "swatchUrl": "/materials/earthenware.png",
    "width": 48,
    "height": 48,
    "textureSha256": "7fe27ce5b78dc540087f86c83ade4be4dad343f9a6a6c3782b3d66ec096af7bf"
  },
  {
    "id": "stoneware",
    "name": "Stoneware",
    "category": "Ceramic",
    "colorHex": "#3c423c",
    "swatchUrl": "/materials/stoneware.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f865613754be35a2623d1404fed873e4b0f078514b52069cdeeaad5a56a3a252"
  },
  {
    "id": "porcelain",
    "name": "Porcelain",
    "category": "Ceramic",
    "colorHex": "#6c5c64",
    "swatchUrl": "/materials/porcelain.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f8e0e900e906881bba57504e07e8de932857e505d5dd5404b86f213d8b2f6820"
  },
  {
    "id": "iron",
    "name": "Iron",
    "category": "Metal",
    "colorHex": "#7f7f81",
    "swatchUrl": "/materials/iron.png",
    "width": 48,
    "height": 48,
    "textureSha256": "4e96dec3f5b46558a6240700f3d50da929bca4be7863ea4d19c28d5634b379b0"
  },
  {
    "id": "lay-pewter",
    "name": "Lay Pewter",
    "category": "Metal",
    "colorHex": "#9c9fa7",
    "swatchUrl": "/materials/lay-pewter.png",
    "width": 48,
    "height": 48,
    "textureSha256": "3fa263e10a3e4ee4021d9eff119a5152fc1d798f7d18a6c2ab7410eff97eb9cf"
  },
  {
    "id": "gold",
    "name": "Gold",
    "category": "Metal",
    "colorHex": "#897152",
    "swatchUrl": "/materials/gold.png",
    "width": 48,
    "height": 48,
    "textureSha256": "616042a42d188d0134cea0b3e4ce4716107f1f99fa8eb12fa6b58b6eae59324b"
  },
  {
    "id": "lead",
    "name": "Lead",
    "category": "Metal",
    "colorHex": "#5f5a59",
    "swatchUrl": "/materials/lead.png",
    "width": 48,
    "height": 48,
    "textureSha256": "3c5115a79be948059a7d92494e8abd43bfce84bcb4782b2ad489ac5e3d5d3a39"
  },
  {
    "id": "silver",
    "name": "Silver",
    "category": "Metal",
    "colorHex": "#8d9096",
    "swatchUrl": "/materials/silver.png",
    "width": 48,
    "height": 48,
    "textureSha256": "fe68e23f29e0c5a63deb10aab56bbef6a4d9afe850517d7514c04be9beea841f"
  },
  {
    "id": "aluminum",
    "name": "Aluminum",
    "category": "Metal",
    "colorHex": "#9c9fa7",
    "swatchUrl": "/materials/aluminum.png",
    "width": 48,
    "height": 48,
    "textureSha256": "d1b88f835614aa9e5d8de0e8a72afc48f02eae236604e113f6fb01001e6c87ef"
  },
  {
    "id": "copper",
    "name": "Copper",
    "category": "Metal",
    "colorHex": "#835849",
    "swatchUrl": "/materials/copper.png",
    "width": 48,
    "height": 48,
    "textureSha256": "877eb4505a53d6101e3be503112ea67a90bac4b9bdec87bf858ed94ab529d92c"
  },
  {
    "id": "nickel-silver",
    "name": "Nickel Silver",
    "category": "Metal",
    "colorHex": "#8d9096",
    "swatchUrl": "/materials/nickel-silver.png",
    "width": 48,
    "height": 48,
    "textureSha256": "82fdbdfa47e65572f05c567090ddd4877283ed36aba84cc2d6fed4750a381c3c"
  },
  {
    "id": "nickel",
    "name": "Nickel",
    "category": "Metal",
    "colorHex": "#8d9096",
    "swatchUrl": "/materials/nickel.png",
    "width": 48,
    "height": 48,
    "textureSha256": "1a2ff1a0e23cff94ab74b0b3703d66e78f4f43777ec98969b47e49fb6f00333f"
  },
  {
    "id": "billon",
    "name": "Billon",
    "category": "Metal",
    "colorHex": "#776c68",
    "swatchUrl": "/materials/billon.png",
    "width": 48,
    "height": 48,
    "textureSha256": "903e0250dcf185d03c22747fff9b6084bcb3ed055660657ddd2dac6d28b1f7c4"
  },
  {
    "id": "zinc",
    "name": "Zinc",
    "category": "Metal",
    "colorHex": "#8d9096",
    "swatchUrl": "/materials/zinc.png",
    "width": 48,
    "height": 48,
    "textureSha256": "33c99f6690de158ee2ce8a1f1b75380401212d679b72032a9fc713ba85bd289f"
  },
  {
    "id": "sterling-silver",
    "name": "Sterling Silver",
    "category": "Metal",
    "colorHex": "#9c9fa7",
    "swatchUrl": "/materials/sterling-silver.png",
    "width": 48,
    "height": 48,
    "textureSha256": "5e087414668e79ef8ba8b392640917cbe34f961934132d32e9a776df14389f85"
  },
  {
    "id": "bronze",
    "name": "Bronze",
    "category": "Metal",
    "colorHex": "#70574c",
    "swatchUrl": "/materials/bronze.png",
    "width": 48,
    "height": 48,
    "textureSha256": "91f30ab03b56e4c7cef7f90d7b5a10f6ed5d0a3361e351d11f8d534b21a11485"
  },
  {
    "id": "black-bronze",
    "name": "Black Bronze",
    "category": "Metal",
    "colorHex": "#4b4c4e",
    "swatchUrl": "/materials/black-bronze.png",
    "width": 48,
    "height": 48,
    "textureSha256": "6008546c1abaff8fd0670e53886d16aad39c733f19a1bd398f4ed62996decdf8"
  },
  {
    "id": "brass",
    "name": "Brass",
    "category": "Metal",
    "colorHex": "#807351",
    "swatchUrl": "/materials/brass.png",
    "width": 48,
    "height": 48,
    "textureSha256": "248ae5f312f31a7ab0115154d202172c109b12e482ccf1371e1465802f7bfec4"
  },
  {
    "id": "rose-gold",
    "name": "Rose Gold",
    "category": "Metal",
    "colorHex": "#946971",
    "swatchUrl": "/materials/rose-gold.png",
    "width": 48,
    "height": 48,
    "textureSha256": "4ffc26ef57aede0cfc4014b6649d4e262fc7a1e8d5db56c9d4f9d7e6abad22d5"
  },
  {
    "id": "steel",
    "name": "Steel",
    "category": "Metal",
    "colorHex": "#888c98",
    "swatchUrl": "/materials/steel.png",
    "width": 48,
    "height": 48,
    "textureSha256": "8adad893da43099ceb90930eeb81604342cc1e5c64b2caeecb99402b2ca09afb"
  },
  {
    "id": "bismuth",
    "name": "Bismuth",
    "category": "Metal",
    "colorHex": "#826682",
    "swatchUrl": "/materials/bismuth.png",
    "width": 48,
    "height": 48,
    "textureSha256": "12662d4fc0081d8d8b26e1d5078e0ee5ae0c34b08417ea3c3b295e213d2baf44"
  },
  {
    "id": "pig-iron",
    "name": "Pig Iron",
    "category": "Metal",
    "colorHex": "#5f5a59",
    "swatchUrl": "/materials/pig-iron.png",
    "width": 48,
    "height": 48,
    "textureSha256": "f4c936ce2c2dd025dbba03b78d5fbc42e5b7aa5bb7e6198d238f274c258f1cab"
  },
  {
    "id": "bismuth-bronze",
    "name": "Bismuth Bronze",
    "category": "Metal",
    "colorHex": "#83796e",
    "swatchUrl": "/materials/bismuth-bronze.png",
    "width": 48,
    "height": 48,
    "textureSha256": "32ad26ab8f7978057d26909beec0ec02425f6728b4bf361eeaa4151803b8d8b4"
  },
  {
    "id": "platinum",
    "name": "Platinum",
    "category": "Metal",
    "colorHex": "#9c9fa7",
    "swatchUrl": "/materials/platinum.png",
    "width": 48,
    "height": 48,
    "textureSha256": "e02aadd4d687489243e50f13f8471084e0ef0bf0544118b2649ff3f364907656"
  },
  {
    "id": "adamantine",
    "name": "Adamantine",
    "category": "Metal",
    "colorHex": "#6f8997",
    "swatchUrl": "/materials/adamantine.png",
    "width": 48,
    "height": 48,
    "textureSha256": "4576e3c20c615833da4e61fc76a41e9fd927fcb88262dcfc3901055ac440c0d6"
  },
  {
    "id": "electrum",
    "name": "Electrum",
    "category": "Metal",
    "colorHex": "#6e5948",
    "swatchUrl": "/materials/electrum.png",
    "width": 48,
    "height": 48,
    "textureSha256": "fdaf736238b26317ffc5ce003476e3a80d4020050d4f01fc8743f507dd95e258"
  },
  {
    "id": "tin",
    "name": "Tin",
    "category": "Metal",
    "colorHex": "#8d9096",
    "swatchUrl": "/materials/tin.png",
    "width": 48,
    "height": 48,
    "textureSha256": "97d1e54547f7f7563e50e7507fdbda58796f84b8ffd406e17fbcf49233ea977d"
  },
  {
    "id": "fine-pewter",
    "name": "Fine Pewter",
    "category": "Metal",
    "colorHex": "#8d9096",
    "swatchUrl": "/materials/fine-pewter.png",
    "width": 48,
    "height": 48,
    "textureSha256": "a195d7b19f91217889a71d26446b7f0a4109a853d952c6c3593f1fcfdf003a5f"
  },
  {
    "id": "trifle-pewter",
    "name": "Trifle Pewter",
    "category": "Metal",
    "colorHex": "#5f5a59",
    "swatchUrl": "/materials/trifle-pewter.png",
    "width": 48,
    "height": 48,
    "textureSha256": "8686fd7b088efe3e9b45de5188f7b3b3da538cf0856470119c79c0e0a06ff523"
  }
] as Material[]
